title: Hacker's blog
email: https://temp-mail.org
description: >- # Ni lo toques
  Esto es el Hacker's blog, aquí iré subiendo cosas y problemas sobre hacking (junto con la solución que le he dado yo) y un poco de programación para que la gente aprenda.
baseurl: "/hacker-s-blog/" 
url: "https://dario-git-hub.github.io/" 
twitter_username: no-tengo-twitter
github_username:  Dario-git-hub

# Build settings
theme: minima
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
